name: Generate Metrics
on:
  schedule: [cron: "0 * * * *"]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: "Africa/Algiers"

          # ğŸ¨ Dark Theme
          config_output: svg
          config_palette: github-dark
          config_display: columns

          # ğŸ† Achievements (GitHub Trophies)
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 6

          # ğŸŒŸ Most Used Languages (With Icons)
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_ignored: "github-readme-stats,tari9bro.github.io"
          plugin_languages_details: percentage, bytes-size, lines, icons
          plugin_languages_limit: 10

          # ğŸ› ï¸ Technologies & Frameworks (With Icons)
          plugin_technology: yes
          plugin_technology_format: list
          plugin_technology_categories: programming, frameworks, tools
          plugin_technology_theme: dark
          plugin_technology_icons: yes
